# Generated by Django 4.1.6 on 2023-02-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collections", "0003_planets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planets",
            name="url",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
