version: '3'

services:
  db:
    image: postgres
    container_name: 'db'
    environment: 
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_PORT=${DB_PORT}

  web:
    build: .
    volumes:
      - static_volume:/src/src/staticfiles
    depends_on:
      - db
    command: sh -c "python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn --bind 0.0.0.0:8000 src.config.wsgi:application"
    environment:
      - PYTHONPATH=./src
    expose:
      - 8000
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/src/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
